openapi: 3.0.1
info:
  contact:
    email: support@emaopay.com
    name: API Support
    url: https://emaopay.com/support
  description: EmaoPay API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://emaopay.com
  title: EmaoPay API
  version: "1.0"
servers:
- url: //emaopay.com/
paths:
  /api/merchants:
    get:
      description: 获取商户列表
      operationId: getMerchantListByUserId
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/emaopay.Merchant'
                type: array
          description: OK
      summary: 获取商户列表
      tags:
      - 商户
    post:
      description: 创建商户
      operationId: createMerchant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateMerchantParams'
        description: 商户
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Merchant'
          description: OK
      summary: 创建商户
      tags:
      - 商户
      x-codegen-request-body-name: merchant
  /api/merchants/:merchantId/messages:
    get:
      description: 获取监控消息列表（商户ID）
      operationId: getMonitorMessageListByMerchantId
      parameters:
      - description: 商户Id
        in: path
        name: merchantId
        required: true
        schema:
          type: string
      - description: 页码
        in: query
        name: pageIndex
        required: true
        schema:
          type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.PagedResponse-emaopay_MonitorMessage'
          description: OK
      summary: 获取监控消息列表（商户ID）
      tags:
      - 监控
  /api/merchants/{id}:
    get:
      description: 获取商户信息
      operationId: getMerchantById
      parameters:
      - description: 商户Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Merchant'
          description: OK
      summary: 获取商户信息
      tags:
      - 商户
    put:
      description: 更新商户
      operationId: updateMerchant
      parameters:
      - description: 商户Id
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateMerchantParams'
        description: 商户
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Merchant'
          description: OK
      summary: 更新商户
      tags:
      - 商户
      x-codegen-request-body-name: merchant
  /api/merchants/new:
    post:
      description: 创建新商户
      operationId: createNewMerchant
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Merchant'
          description: OK
      summary: 创建新商户
      tags:
      - 商户
  /api/monitors:
    get:
      description: 获取监控列表
      operationId: getMonitorListByMerchantId
      parameters:
      - description: 商户Id
        in: query
        name: merchantId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/emaopay.Monitor'
                type: array
          description: OK
      summary: 获取监控列表
      tags:
      - 监控
    post:
      description: 创建监控
      operationId: createMonitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateMonitorParams'
        description: 监控
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Monitor'
          description: OK
      summary: 创建监控
      tags:
      - 监控
      x-codegen-request-body-name: monitor
  /api/monitors/:monitorId/messages:
    get:
      description: 获取监控消息列表（商户监控）
      operationId: getMonitorMessageListByMonitorId
      parameters:
      - description: 监控Id
        in: path
        name: monitorId
        required: true
        schema:
          type: string
      - description: 页码
        in: query
        name: pageIndex
        required: true
        schema:
          type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.PagedResponse-emaopay_MonitorMessage'
          description: OK
      summary: 获取监控消息列表（商户监控）
      tags:
      - 监控
  /api/monitors/{id}:
    delete:
      description: 删除监控
      operationId: deleteMonitorById
      parameters:
      - description: 监控Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          content: {}
          description: No Content
      summary: 删除监控
      tags:
      - 监控
    get:
      description: 获取监控
      operationId: getMonitorById
      parameters:
      - description: 监控Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Monitor'
          description: OK
      summary: 获取监控
      tags:
      - 监控
    put:
      description: 更新监控
      operationId: updateMonitor
      parameters:
      - description: 监控Id
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateMonitorParams'
        description: 监控
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Monitor'
          description: OK
      summary: 更新监控
      tags:
      - 监控
      x-codegen-request-body-name: monitor
  /api/monitors/{monitorId}/refresh-api-token:
    put:
      description: 刷新ApiToken
      operationId: refreshMonitorApiToken
      parameters:
      - description: 监控Id
        in: path
        name: monitorId
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: OK
      summary: 刷新ApiToken
      tags:
      - 监控
  /api/monitors/messages:
    get:
      description: 检查服务状态
      operationId: checkServiceStatus
      parameters:
      - description: 监控Id
        in: header
        name: X-Monitor-Id
        required: true
        schema:
          type: string
      - description: ApiToken
        in: header
        name: X-Token
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: OK
      summary: 检查服务状态
      tags:
      - 监控
    post:
      description: 推送消息
      operationId: pushMessage
      parameters:
      - description: 监控Id
        in: header
        name: X-Monitor-Id
        required: true
        schema:
          type: string
      - description: ApiToken
        in: header
        name: X-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.MonitorMessageParams'
        description: 监控消息
        required: true
      responses:
        "201":
          content: {}
          description: Created
        "204":
          content: {}
          description: No Content
      summary: 推送消息
      tags:
      - 监控
      x-codegen-request-body-name: monitorMessage
  /api/monitors/new:
    post:
      description: 创建新监控
      operationId: createNewMonitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateNewMonitorParams'
        description: 监控
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Monitor'
          description: OK
      summary: 创建新监控
      tags:
      - 监控
      x-codegen-request-body-name: monitor
  /api/orders:
    get:
      description: 获取订单列表
      operationId: getPagedOrderList
      parameters:
      - description: 订单状态
        in: path
        name: status
        required: true
        schema:
          type: string
      - description: 商户Id
        in: path
        name: merchantId
        required: true
        schema:
          type: string
      - description: 产品Id
        in: path
        name: productId
        required: true
        schema:
          type: string
      - description: 页码
        in: query
        name: pageIndex
        required: true
        schema:
          type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/emaopay.PagedResponse-emaopay_Order'
                type: array
          description: OK
      summary: 获取订单列表
      tags:
      - 订单
    post:
      description: 创建订单
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateOrderParams'
        description: 订单
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Order'
          description: OK
      summary: 创建订单
      tags:
      - 订单
      x-codegen-request-body-name: params
  /api/orders/{id}:
    get:
      description: 获取订单信息
      operationId: getOrderById
      parameters:
      - description: 订单Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Order'
          description: OK
      summary: 获取订单信息
      tags:
      - 订单
  /api/orders/finish/{id}:
    post:
      description: 手动完成订单
      operationId: finishedOrderById
      parameters:
      - description: 订单Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Order'
          description: OK
      summary: 手动完成订单
      tags:
      - 订单
  /api/orders/notify/{id}:
    post:
      description: 通知订单回调
      operationId: notifyOrderById
      parameters:
      - description: 订单Id
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.Order'
          description: OK
      summary: 通知订单回调
      tags:
      - 订单
  /api/orders/payment-providers:
    get:
      description: 获取支付方式
      operationId: getPaymentProviders
      parameters:
      - description: 订单Id
        in: query
        name: merchantId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: OK
      summary: 获取支付方式
      tags:
      - 订单
  /api/orders/user:
    get:
      description: 获取订单列表
      operationId: getOrderListByUserId
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/emaopay.Order'
                type: array
          description: OK
      summary: 获取订单列表
      tags:
      - 订单
  /api/qrcodes:
    delete:
      description: 删除二维码
      operationId: deleteQrCodeById
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.DeleteQrCodeParams'
        description: 二维码
        required: true
      responses:
        "204":
          content: {}
          description: No Content
      summary: 删除二维码
      tags:
      - 二维码
      x-codegen-request-body-name: qrCode
    get:
      description: 获取二维码列表
      operationId: getQrCodePagedListByMonitorId
      parameters:
      - description: 商户Id
        in: query
        name: monitorId
        required: true
        schema:
          type: string
      - description: 页码
        in: query
        name: pageIndex
        schema:
          type: integer
      - description: 每页数量
        in: query
        name: pageSize
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.PagedResponse-emaopay_QrCode'
          description: OK
      summary: 获取二维码列表
      tags:
      - 二维码
    post:
      description: 创建二维码
      operationId: createQrCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.CreateQrCodeParams'
        description: 二维码
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.QrCode'
          description: No Content
      summary: 创建二维码
      tags:
      - 二维码
      x-codegen-request-body-name: qrCode
  /api/qrcodes/upload-credits:
    get:
      description: 获取二维码上传凭证
      operationId: getQrCodeUploadCredits
      parameters:
      - description: 商户Id
        in: query
        name: merchantId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.UploadCredits'
          description: OK
      summary: 获取二维码上传凭证
      tags:
      - 二维码
  /api/user/info:
    get:
      description: 获取用户信息
      operationId: getUserInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.User'
          description: OK
      summary: 获取用户信息
      tags:
      - 用户
  /api/user/login:
    post:
      description: 登录
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.LoginParams'
        description: 登录参数
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emaopay.LoginResponse'
          description: OK
      summary: 登录
      tags:
      - 用户
      x-codegen-request-body-name: params
  /api/user/register:
    post:
      description: 注册
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emaopay.RegisterParams'
        description: 注册参数
        required: true
      responses:
        "200":
          content: {}
          description: OK
      summary: 注册
      tags:
      - 用户
      x-codegen-request-body-name: params
components:
  schemas:
    emaopay.CreateMerchantParams:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    emaopay.CreateMonitorParams:
      properties:
        merchantId:
          type: string
        name:
          type: string
        weight:
          type: integer
      required:
      - merchantId
      - name
      - weight
      type: object
    emaopay.CreateNewMonitorParams:
      properties:
        merchantId:
          type: string
      required:
      - merchantId
      type: object
    emaopay.CreateOrderParams:
      properties:
        amount:
          description: 金额
          type: string
        merchantId:
          description: 商户 Id
          type: string
        merchantTradeNo:
          description: "商户订单号, 对商户而言是唯一的"
          type: string
        notifyURL:
          description: 回调地址
          type: string
        paymentMethod:
          description: 支付方式
          type: string
        productId:
          description: 产品 Id
          type: string
        returnURL:
          description: 支付成功后的跳转地址
          type: string
        signature:
          description: 签名
          type: string
        userId:
          description: "用户 Id, 可为空，如果是匿名用户，那么就为空"
          type: string
      type: object
    emaopay.CreateQrCodeParams:
      properties:
        imageKeys:
          items:
            type: string
          type: array
        merchantId:
          type: string
        monitorId:
          type: string
      type: object
    emaopay.Credentials:
      properties:
        tmpSecretId:
          description: 临时证书密钥ID
          type: string
        tmpSecretKey:
          description: 临时证书密钥Key
          type: string
        token:
          description: token
          type: string
      type: object
    emaopay.DeleteQrCodeParams:
      properties:
        ids:
          items:
            type: string
          type: array
      type: object
    emaopay.LoginParams:
      properties:
        password:
          type: string
        username:
          type: string
      type: object
    emaopay.LoginResponse:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    emaopay.Merchant:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        deletedAt: 2000-01-23T04:56:07.000+00:00
        name: name
        id: id
        userId: userId
        key: key
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        id:
          type: string
        key:
          type: string
        name:
          type: string
        updatedAt:
          format: date-time
          type: string
        userId:
          type: string
      type: object
    emaopay.Monitor:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        deletedAt: 2000-01-23T04:56:07.000+00:00
        apiToken: apiToken
        merchantId: merchantId
        name: name
        weight: 0
        id: id
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        apiToken:
          type: string
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        id:
          type: string
        merchantId:
          type: string
        name:
          type: string
        updatedAt:
          format: date-time
          type: string
        weight:
          description: 几率权重， 0到100之间
          type: integer
      type: object
    emaopay.MonitorMessage:
      example:
        monitorId: monitorId
        handled: true
        packageName: packageName
        content: content
        timestamp: 0
      properties:
        content:
          type: string
        handled:
          type: boolean
        monitorId:
          type: string
        packageName:
          type: string
        timestamp:
          type: integer
      type: object
    emaopay.MonitorMessageParams:
      properties:
        content:
          type: string
        packageName:
          type: string
        timestamp:
          type: integer
      type: object
    emaopay.Order:
      example:
        amount: amount
        merchantTradeNo: merchantTradeNo
        monitorId: monitorId
        productId: productId
        signature: signature
        created: 0
        userId: userId
        realAmount: realAmount
        createdAt: 2000-01-23T04:56:07.000+00:00
        expiredAt: 6
        deletedAt: 2000-01-23T04:56:07.000+00:00
        qrCode: qrCode
        merchantId: merchantId
        notifySuccessAt: 5
        notifyURL: notifyURL
        paidAt: 5
        paymentMethod: paymentMethod
        id: id
        returnURL: returnURL
        notifyFailedCount: 1
        status: status
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        amount:
          description: 金额
          type: string
        created:
          description: 创建时间戳
          type: integer
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        expiredAt:
          description: 超时时间
          type: integer
        id:
          type: string
        merchantId:
          description: 商户 Id
          type: string
        merchantTradeNo:
          description: "商户订单号, 对商户而言是唯一的"
          type: string
        monitorId:
          description: 监控 Id
          type: string
        notifyFailedCount:
          description: 通知失败次数
          type: integer
        notifySuccessAt:
          description: 通知成功时间
          type: integer
        notifyURL:
          description: 回调地址
          type: string
        paidAt:
          description: 更新时间戳
          type: integer
        paymentMethod:
          description: 支付方式
          type: string
        productId:
          description: "产品 Id, 可为空"
          type: string
        qrCode:
          description: 二维码
          type: string
        realAmount:
          description: 真实金额
          type: string
        returnURL:
          description: 支付成功后的跳转地址
          type: string
        signature:
          description: 签名
          type: string
        status:
          description: 状态
          type: string
        updatedAt:
          format: date-time
          type: string
        userId:
          description: "用户 Id, 可为空，如果是匿名用户，那么就为空"
          type: string
      type: object
    emaopay.PagedResponse-emaopay_MonitorMessage:
      example:
        total: 6
        data:
        - monitorId: monitorId
          handled: true
          packageName: packageName
          content: content
          timestamp: 0
        - monitorId: monitorId
          handled: true
          packageName: packageName
          content: content
          timestamp: 0
      properties:
        data:
          items:
            $ref: '#/components/schemas/emaopay.MonitorMessage'
          type: array
        total:
          type: integer
      type: object
    emaopay.PagedResponse-emaopay_Order:
      example:
        total: 2
        data:
        - amount: amount
          merchantTradeNo: merchantTradeNo
          monitorId: monitorId
          productId: productId
          signature: signature
          created: 0
          userId: userId
          realAmount: realAmount
          createdAt: 2000-01-23T04:56:07.000+00:00
          expiredAt: 6
          deletedAt: 2000-01-23T04:56:07.000+00:00
          qrCode: qrCode
          merchantId: merchantId
          notifySuccessAt: 5
          notifyURL: notifyURL
          paidAt: 5
          paymentMethod: paymentMethod
          id: id
          returnURL: returnURL
          notifyFailedCount: 1
          status: status
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - amount: amount
          merchantTradeNo: merchantTradeNo
          monitorId: monitorId
          productId: productId
          signature: signature
          created: 0
          userId: userId
          realAmount: realAmount
          createdAt: 2000-01-23T04:56:07.000+00:00
          expiredAt: 6
          deletedAt: 2000-01-23T04:56:07.000+00:00
          qrCode: qrCode
          merchantId: merchantId
          notifySuccessAt: 5
          notifyURL: notifyURL
          paidAt: 5
          paymentMethod: paymentMethod
          id: id
          returnURL: returnURL
          notifyFailedCount: 1
          status: status
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          items:
            $ref: '#/components/schemas/emaopay.Order'
          type: array
        total:
          type: integer
      type: object
    emaopay.PagedResponse-emaopay_QrCode:
      example:
        total: 6
        data:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          amount: amount
          deletedAt: 2000-01-23T04:56:07.000+00:00
          monitorId: monitorId
          merchantId: merchantId
          provider: provider
          unlockAt: 0
          id: id
          content: content
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          amount: amount
          deletedAt: 2000-01-23T04:56:07.000+00:00
          monitorId: monitorId
          merchantId: merchantId
          provider: provider
          unlockAt: 0
          id: id
          content: content
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          items:
            $ref: '#/components/schemas/emaopay.QrCode'
          type: array
        total:
          type: integer
      type: object
    emaopay.QrCode:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        amount: amount
        deletedAt: 2000-01-23T04:56:07.000+00:00
        monitorId: monitorId
        merchantId: merchantId
        provider: provider
        unlockAt: 0
        id: id
        content: content
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        amount:
          type: string
        content:
          type: string
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        id:
          type: string
        merchantId:
          type: string
        monitorId:
          type: string
        provider:
          description: "二维码提供商, 如: wechat, alipay"
          type: string
        unlockAt:
          description: "解锁时间, unix时间戳, 0表示未锁定"
          type: integer
        updatedAt:
          format: date-time
          type: string
      type: object
    emaopay.RegisterParams:
      properties:
        password:
          type: string
        username:
          type: string
      type: object
    emaopay.UploadCredits:
      example:
        bucket: bucket
        credentials: "{}"
        expiration: expiration
        region: region
        expiredTime: 0
      properties:
        bucket:
          description: 存储桶名
          type: string
        credentials:
          allOf:
          - $ref: '#/components/schemas/emaopay.Credentials'
          description: 临时证书
          type: object
        expiration:
          description: |-
            证书有效的时间，以 iso8601 格式的 UTC 时间表示
            注意：此字段可能返回 null，表示取不到有效值。
          type: string
        expiredTime:
          description: 临时证书有效的时间，返回 Unix 时间戳，精确到秒
          type: integer
        region:
          description: 区域
          type: string
      type: object
    emaopay.User:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        deletedAt: 2000-01-23T04:56:07.000+00:00
        role: role
        balance: balance
        id: id
        email: email
        updatedAt: 2000-01-23T04:56:07.000+00:00
        username: username
      properties:
        balance:
          type: string
        createdAt:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        email:
          type: string
        id:
          type: string
        role:
          type: string
        updatedAt:
          format: date-time
          type: string
        username:
          type: string
      type: object
x-original-swagger-version: "2.0"
